##### Practical 2: Data Cleaning and Organization of Supermarket Data
Dataset: Superstore Sales Dataset

###### 1. Import Libraries and Load Dataset

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("superstore_sales_cleaned.xlsx")
print("Shape:", df.shape)
df.head()

Shape: (9788, 17)

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

###### 2. Check Data Types and Missing Values

In [2]:
print("Data Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isnull().sum())

Data Types:
 Order_ID                 object
Order_Date       datetime64[ns]
Ship_Date        datetime64[ns]
Ship_Mode                object
Customer_ID              object
Customer_Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal_Code               int64
Region                   object
Product_ID               object
Category                 object
Sub_Category             object
Product_Name             object
Sales                   float64
dtype: object

Missing Values:
 Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
City             0
State            0
Postal_Code      0
Region           0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
dtype: int64

###### 3. Handle Null Values

In [8]:
# Fill numeric nulls with mean, categorical with mode
for col in df.select_dtypes(include=[np.number]).columns:
    df[col].fillna(df[col].mean(), inplace=True)

for col in df.select_dtypes(include=['object']).columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("Null values after handling:", df.isnull().sum().sum())

Null values after handling: 0

###### 4. Remove Duplicates

In [4]:
print("Duplicates before:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

###### 5. Fix Column Types

In [5]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'])
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
df['Postal_Code'] = df['Postal_Code'].astype(str)

print("Updated Data Types:\n", df.dtypes)

Updated Data Types:
 Order_ID                 object
Order_Date       datetime64[ns]
Ship_Date        datetime64[ns]
Ship_Mode                object
Customer_ID              object
Customer_Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal_Code              object
Region                   object
Product_ID               object
Category                 object
Sub_Category             object
Product_Name             object
Sales                   float64
dtype: object

###### 6. Format Dates

In [6]:
df['Order_Date_Formatted'] = df['Order_Date'].dt.strftime('%d-%m-%Y')
df['Ship_Date_Formatted'] = df['Ship_Date'].dt.strftime('%d-%m-%Y')

print("Formatted dates:")
df[['Order_Date', 'Order_Date_Formatted', 'Ship_Date', 'Ship_Date_Formatted']].head()

Formatted dates:

  Order_Date Order_Date_Formatted  Ship_Date Ship_Date_Formatted
0 2017-11-08           08-11-2017 2017-11-11          11-11-2017
1 2017-11-08           08-11-2017 2017-11-11          11-11-2017
2 2017-06-12           12-06-2017 2017-06-16          16-06-2017
3 2016-10-11           11-10-2016 2016-10-18          18-10-2016
4 2016-10-11           11-10-2016 2016-10-18          18-10-2016

###### 7. Verify and Save Cleaned Data

In [7]:
print("Final Shape:", df.shape)
print("Null Values:", df.isnull().sum().sum())
df.to_excel("superstore_sales_final_cleaned.xlsx", index=False)
print("Saved as superstore_sales_final_cleaned.xlsx")
df.head()

Final Shape: (9788, 19)
Null Values: 0
Saved as superstore_sales_final_cleaned.xlsx

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Order_Date_Formatted,Ship_Date_Formatted
0,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,08-11-2017,11-11-2017
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,08-11-2017,11-11-2017
2,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,12-06-2017,16-06-2017
3,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,11-10-2016,18-10-2016
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680,11-10-2016,18-10-2016